import Preloader from "@/layouts/Preloader";
import "@css/main.css";
import { DM_Sans, Inter } from "next/font/google";
import "react-nice-select/css/nice-select.css";
import "./globals.css";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--headingFont",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--paraFont",
  display: "swap",
});

export const metadata = {
  title: "Contis - AI Content Writing React NextJS Template",
  description: "Generated by create next app",
};

const fontFamily = `${dm_sans.variable} ${inter.variable}`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
