"use client";
import { useState } from "react";
import { Accordion } from "react-bootstrap";

const faqData = [
  {
    id: 1,
    title: "What is an AI writer website?",
    desc: "An AI writer website is a platform that uses artificial intelligence to generate written content. It can create articles, blog posts, marketing copy, and more, often with minimal human intervention. An AI writer website is a platform that uses artificial intelligence to generate written content. It can create articles, blog posts, marketing copy, and more, often with minimal human intervention.",
  },
  {
    id: 2,
    title: "How does AI writing work?",
    desc: "AI writing is powered by machine learning models that have been trained on vast amounts of text data. These models can generate text based on the input they receive, making them capable of producing human-like content. AI writing is powered by machine learning models that have been trained on vast amounts of text data. These models can generate text based on the input they receive, making them capable of producing human-like content.",
  },
  {
    id: 3,
    title: "What can I use AI writing for?",
    desc: "Yes, the content generated by AI is typically original, but it's essential to review and edit it to ensure it meets your specific needs and avoids plagiarism.Yes, the content generated by AI is typically original, but it's essential to review and edit it to ensure it meets your specific needs and avoids plagiarism.Yes, the content generated by AI is typically original, but it's essential to review and edit it to ensure it meets your specific needs and avoids plagiarism.",
  },
  {
    id: 4,
    title: "Is the content generated by AI original?",
    desc: "AI writing can be used for a variety of purposes, such as creating blog content, product descriptions, social media posts, email newsletters, and more. It's a versatile tool for generating written material.AI writing can be used for a variety of purposes, such as creating blog content, product descriptions, social media posts, email newsletters, and more. It's a versatile tool for generating written material.",
  },
  {
    id: 5,
    title: "How do I use an AI writer website?",
    desc: "Using an AI writer website is usually straightforward. You input your requirements or prompts, and the AI generates content based on that input. You can then edit and refine the content as needed. Using an AI writer website is usually straightforward. You input your requirements or prompts, and the AI generates content based on that input. You can then edit and refine the content as needed.",
  },
];
const Faq = () => {
  const [active, setActive] = useState(1);
  return (
    <Accordion
      defaultActiveKey="collaps-1"
      className="accordion tf__faq_accordion"
      id="accordionExample01"
    >
      {faqData.map((faq) => (
        <div className="accordion-item" key={faq.id}>
          <h2 className="accordion-header" id="headingOne">
            <Accordion.Toggle
              className={`accordion-button ${
                faq.id == active ? "" : "collapsed"
              }`}
              as="button"
              eventKey={`collaps-${faq.id}`}
              onClick={() => setActive(faq.id == active ? 0 : faq.id)}
            >
              {faq.title}
            </Accordion.Toggle>
          </h2>
          <Accordion.Collapse
            eventKey={`collaps-${faq.id}`}
            className="accordion-collapse"
          >
            <div className="accordion-body">
              <p>{faq.desc}</p>
            </div>
          </Accordion.Collapse>
        </div>
      ))}
    </Accordion>
  );
};
export default Faq;

const faq2Data = [
  {
    id: 1,
    title: "Choose the sort of content copy you wish to create.",
    desc: "Get your thoughts to paper faster with our step-by-step AI copywriter.",
  },
  {
    id: 2,
    title: "Enter the specifics of your product or business.",
    desc: "Get your thoughts to paper faster with our step-by-step AI copywriter.",
  },
  {
    id: 3,
    title: "See how AI is used to generate creative content clones.",
    desc: "Get your thoughts to paper faster with our step-by-step AI copywriter.",
  },
];
export const Faq2 = () => {
  const [active, setActive] = useState(1);
  return (
    <Accordion
      defaultActiveKey="collapse-1"
      className="accordion"
      id="accordionExample"
    >
      {faq2Data.map((faq) => (
        <div className="accordion-item" key={faq.id}>
          <h2 className="accordion-header" id="headingOne01">
            <Accordion.Toggle
              as={"button"}
              className={`accordion-button tf__process_accordion_btn ${
                faq.id == active ? "" : "collapsed"
              }`}
              eventKey={`collapse-${faq.id}`}
              onClick={() => setActive(faq.id == active ? 0 : faq.id)}
            >
              <span>{faq.id}</span>
              {faq.title}
            </Accordion.Toggle>
          </h2>
          <Accordion.Collapse
            eventKey={`collapse-${faq.id}`}
            className={`accordion-collapse`}
            aria-labelledby="headingOne01"
            data-bs-parent="#accordionExample"
          >
            <div className="accordion-body">
              <p>{faq.desc}</p>
              <a href="#" className="tf__common_btn tf__accrodian_link">
                Get Started
                <i className="fa-regular fa-arrow-right-long" />
              </a>
            </div>
          </Accordion.Collapse>
        </div>
      ))}
    </Accordion>
  );
};
